/// Collects cumulative release notes from GitHub Releases API payloads.
library;

/// Strips a leading `v` from a release tag.
String normalizeTagVersion(String tag) {
  final trimmed = tag.trim();
  if (trimmed.startsWith('v') || trimmed.startsWith('V')) {
    return trimmed.substring(1);
  }
  return trimmed;
}

/// Semver-ish comparison: negative if [a] < [b], zero if equal, positive if [a] > [b].
int compareAppVersions(String a, String b) {
  final aParts = _parseVersion(a);
  final bParts = _parseVersion(b);
  final length = aParts.length > bParts.length ? aParts.length : bParts.length;
  for (var i = 0; i < length; i++) {
    final av = i < aParts.length ? aParts[i] : 0;
    final bv = i < bParts.length ? bParts[i] : 0;
    if (av != bv) return av.compareTo(bv);
  }
  return 0;
}

bool isAppVersionNewer(String remote, String local) =>
    compareAppVersions(remote, local) > 0;

/// Builds markdown for releases in `(currentVersion, latestVersion]`.
String? collectReleaseNotesMarkdown({
  required List<Map<String, dynamic>> releases,
  required String currentVersion,
  required String latestVersion,
}) {
  final sections = <String>[];

  for (final release in releases) {
    if (release['draft'] == true || release['prerelease'] == true) continue;

    final tag = release['tag_name'] as String? ?? '';
    if (tag.isEmpty) continue;

    final version = normalizeTagVersion(tag);
    if (!isAppVersionNewer(version, currentVersion)) continue;
    if (isAppVersionNewer(version, latestVersion)) continue;

    final body = (release['body'] as String? ?? '').trim();
    if (body.isEmpty || _isAutoGeneratedReleaseBody(body)) continue;

    sections.add('## v$version\n\n$body');
  }

  if (sections.isEmpty) return null;
  return sections.join('\n\n');
}

bool _isAutoGeneratedReleaseBody(String body) {
  final lines = body
      .split('\n')
      .map((line) => line.trim())
      .where((line) => line.isNotEmpty)
      .toList();
  if (lines.length != 1) return false;
  return lines.first.startsWith('**Full Changelog**:');
}

List<int> _parseVersion(String raw) {
  return raw
      .split('+')
      .first
      .split('.')
      .map((part) => int.tryParse(part.trim()) ?? 0)
      .toList();
}
